"""Agrega lat/lon a Canton

Revision ID: 01d4bce9dc97
Revises: aa8ab24009bf
Create Date: 2025-06-08 13:14:30.507476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01d4bce9dc97'
down_revision: Union[str, None] = 'aa8ab24009bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('canton', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('canton', sa.Column('lon', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('canton', 'lon')
    op.drop_column('canton', 'lat')
    # ### end Alembic commands ###
