"""Add calificacion to Orden

Revision ID: 32eb3016fdbf
Revises: 83d4ae0e8ba3
Create Date: 2025-06-13 23:20:06.420854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32eb3016fdbf'
down_revision: Union[str, None] = '83d4ae0e8ba3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orden', sa.Column('calificacion', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orden', 'calificacion')
    # ### end Alembic commands ###
