"""add imagen_url to vehiculo

Revision ID: 83d4ae0e8ba3
Revises: de1f91d4227e
Create Date: 2025-06-13 22:11:16.450659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83d4ae0e8ba3'
down_revision: Union[str, None] = 'de1f91d4227e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehiculo', sa.Column('imagen_url', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehiculo', 'imagen_url')
    # ### end Alembic commands ###
