"""add testimonio model

Revision ID: b08b7e2e5f98
Revises: 32eb3016fdbf
Create Date: 2025-06-17 18:23:56.549661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b08b7e2e5f98'
down_revision: Union[str, None] = '32eb3016fdbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testimonio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo_usuario', sa.String(length=50), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('avatar_url', sa.String(length=200), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testimonio')
    # ### end Alembic commands ###
