"""Add calificacion to Viaje

Revision ID: fc9a8eec3665
Revises: 9e4f4d4e86d6
Create Date: 2025-06-08 19:42:33.596100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc9a8eec3665'
down_revision: Union[str, None] = '9e4f4d4e86d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viaje', sa.Column('calificacion', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('viaje', 'calificacion')
    # ### end Alembic commands ###
